from model.client import Client
from model.address import Address
from model.truck import Truck
from model.user import User
from model.employee import Employee
from model.mechanic import Mechanic
from model.service import Part
from model.service import Service
from model.parts_stock import PartsStock
